// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC95pO1cRER_xizh8pX4YgZccf5opSXIo',
    appId: '1:886495442955:web:032bdbca13dff5740aaf0e',
    messagingSenderId: '886495442955',
    projectId: 'travelcompanion-11f22',
    authDomain: 'travelcompanion-11f22.firebaseapp.com',
    storageBucket: 'travelcompanion-11f22.firebasestorage.app',
    measurementId: 'G-HMD3SW7E0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY6-3d03eoOdJq14Y7NvqBmlo2pGDpzZ0',
    appId: '1:886495442955:android:9e546775e459ba7b0aaf0e',
    messagingSenderId: '886495442955',
    projectId: 'travelcompanion-11f22',
    storageBucket: 'travelcompanion-11f22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK6nCVNAjWr9z4mkwNWgNsOeB6vGy36yI',
    appId: '1:886495442955:ios:38860d6329d6e38c0aaf0e',
    messagingSenderId: '886495442955',
    projectId: 'travelcompanion-11f22',
    storageBucket: 'travelcompanion-11f22.firebasestorage.app',
    iosBundleId: 'com.example.travelcompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK6nCVNAjWr9z4mkwNWgNsOeB6vGy36yI',
    appId: '1:886495442955:ios:38860d6329d6e38c0aaf0e',
    messagingSenderId: '886495442955',
    projectId: 'travelcompanion-11f22',
    storageBucket: 'travelcompanion-11f22.firebasestorage.app',
    iosBundleId: 'com.example.travelcompanion',
  );
}
